#!/bin/bash
# This script installs Apache and starts the service
apt update -y    # Update package index
apt install apache2 -y    # Install Apache
systemctl start apache2   # Start Apache
systemctl enable apache2  # Enable on boot
